language: go

go:
  - 1.13.x

before_script:
  - make modules
  - make prereq

script:
  - make test+ci
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
