http:
  address: 0.0.0.0:8080
proxy:
  address:
  login:
  pass:
telegram:
  token:
sms:
  incoming: /var/spool/sms/incoming/
  outgoing: /var/spool/sms/outgoing/
email:
  from:
  subject: "Home Alert"
  smtp: smtp.gmail.com
  smtp_port: 587
  login:
  pass:
